server:
  port: 83

#摘自阿里巴巴官网https://spring-cloud-alibaba-group.github.io/github-pages/greenwich/spring-cloud-alibaba.html
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址

#消费者将要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider