server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: lk123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lucky.springcloud.entity

eureka:
  instance:
    instance-id: payment8001 #暴露给eureka的主机名
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1 #发送心跳时间间隔
    lease-expiration-duration-in-seconds: 2 #发送心跳时间间隔上限，超时被剔除服务
  client:
    # 表示是否将自己注册进Eureka。默认为true
    register-with-eureka: true
    # 表示是否从Eureka抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true这样才能配合ribbon使用负载平衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      #当为eureka集群时要将服务同时注册到所有的eureka服务器以免主eureka宕机导致找不到eureka，这养就没有主次之分了
#      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      defaultZone: http://eureka7001.com:7001/eureka